//
//  LoginScenePresenter.swift
//  CleanVIPA
//
//  Created by Niraj Paul on 19/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias LoginScenePresenterInput = LoginInteractorOutput
typealias LoginScenePresenterOutput = LoginViewControllerInput

final class LoginScenePresenter {
    weak var viewController: LoginScenePresenterOutput?
}

extension LoginScenePresenter: LoginScenePresenterInput{
    func showLogingSuccess(user: CleanLoginUser) {
        self.viewController?.showLogInSuccess(fullUserName: user.firstName + " " + user.lastName)
    }
    
    func showLogingFailure(message: String) {
        self.viewController?.showLogInFailure(message: "Something is failed on our side")
    }

}

