//
//  LoginSceneViewController.swift
//  CleanVIPA
//
//  Created by Niraj Paul on 19/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginViewControllerInput:AnyObject {
    func showLogInSuccess(fullUserName: String)
    func showLogInFailure(message: String)
}

protocol LoginSceneViewControllerOutPut:AnyObject {
    func tryToLoginIn()
}

final class LoginViewController: UIViewController {
  
    @IBOutlet weak var txtV: UITextField!
    var interactor: LoginSceneInteractorInput?
    var router: LoginSceneRoutingLogic?
    var myText: String?
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    @IBAction func btnAction(_ sender: Any) {
        interactor?.tryToLoginIn()
    }
    
}
extension LoginViewController: LoginViewControllerInput {
    func showLogInSuccess(fullUserName: String) {
        print(fullUserName)
        self.txtV.text = fullUserName
     
    }
    
    func showLogInFailure(message: String) {
        print(message)
     
    }
}
