//
//  LoginSceneWorker.swift
//  CleanVIPA
//
//  Created by Niraj Paul on 19/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol LoginSceneAuthLogic {
    func makeAuth(
        completion: @escaping (Result<CleanLoginUser, LoginSceneAuthWorker.LoginSceneAuthWorkerError>
        ) -> Void)
}
class LoginSceneAuthWorker
{
    enum LoginSceneAuthWorkerError: Error {
        case authFailed(String)
        case unauthorized
    }
}
extension LoginSceneAuthWorker: LoginSceneAuthLogic {
    func makeAuth(
        completion: @escaping (Result<CleanLoginUser, LoginSceneAuthWorkerError>
        ) -> Void) {
        let userModel
            = CleanLoginUser(firstName: "Niraj",
                             lastName: "Paul")
        completion(.success(userModel))
    }
}
